kind: pipeline
type: docker
name: default

steps:
- name: Test and build binary
  image: golang:1.15-buster
  commands:
    - 'make server'
    - 'make go-unit-tests'

- name: Lint JS code
  image: pipelinecomponents/eslint:02bbbc8
  commands:
    - 'eslint static/js/'

- name: Build and publish container image
  image: banzaicloud/drone-kaniko:0.5.1
  settings:
    repo: jacksgt/u9k
    tags:
      - ${DRONE_TAG}
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
  when:
    ref:
      - refs/tags/*

- name: Push to GitHub
  image: appleboy/drone-git-push
  settings:
    branch: master
    remote: git@github.com:jacksgt/u9k.git
    followtags: true
    ssh_key:
      from_secret: github_private_key
  when:
    branch:
      - master
